language: python
python:
  - "3.3"

# command to install dependencies
install:
  - "pip install ."
  - "python setup.py test"  # for installing `tests_require`
  - "pip install nose-cov"  # why `nose-cov` isn't correctlly installed by `setup.py test` ?

# command to run tests
script:
  - "python manage.py test"

branches:
  only:
    - master
    - dev
